name: build 

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Checkout repository content
      uses: actions/checkout@master
    - name: Install packages
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas geojson
    - name: Execute Python file.
      run: |
          python src/csv_to_geojson.py
    - name: update repo
      run: |
        git config user.email ${{ secrets.EMAIL }}
        git config user.name "Ben"
        git config user.username ben-n93
        git config user.password ${{ secrets.PERSONAL_ACCESS_TOKEN}}
        git add --all
        git commit -m "update"
        git push
